apiVersion: v1
kind: Service
metadata:
  name: product-recommendation
  labels:
    app: product-recommendation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: product-recommendation